REMOTE="gdrive"
REMOTE_PATH="Learning/Obsidian/Samsara/Learn/Gen AI/AI Skills & Configurations"
LOCAL_PATH="/home/susamn/dotfiles/workspace/aistuff"
SYNC_TYPE="one"
USER="susamn"
DIRECTION="local-to-remote"
SCHEDULE="*:0/1"
RCLONE_OPTS="--exclude=/.git/** --exclude=/.git"
