REMOTE="gdrive"
REMOTE_PATH="Media/Music"
LOCAL_PATH="/home/susamn/Music/susamn-music-playlists"
SYNC_TYPE="one"
USER="susamn"
DIRECTION="remote-to-local"
SCHEDULE="*:0/3"
RCLONE_OPTS="--include=*.m3u"
