REMOTE="gdrive"
REMOTE_PATH="Media/Music"
LOCAL_PATH="/home/susamn/Music/susamn-music-collection"
SYNC_TYPE="one"
USER="susamn"
DIRECTION="remote-to-local"
SCHEDULE="*:0/30"
RCLONE_OPTS="--exclude=*.m3u8"
