# Powerlevel10k colors generated by matugen
# This file is auto-generated. Do not edit manually.

# Helper function to convert hex to 256 color
function hex_to_256() {
  local hex=$1
  # Remove # if present
  hex=${hex#\#}

  # Convert hex to RGB
  local r=$((16#${hex:0:2}))
  local g=$((16#${hex:2:2}))
  local b=$((16#${hex:4:2}))

  # Simple approximation to 256 color palette
  # Use 16 + 36*r + 6*g + b where r,g,b are 0-5
  local r6=$(( r * 6 / 256 ))
  local g6=$(( g * 6 / 256 ))
  local b6=$(( b * 6 / 256 ))

  echo $((16 + 36 * r6 + 6 * g6 + b6))
}

# Material You colors from matugen
export MATUGEN_PRIMARY="#fcb0d7"
export MATUGEN_SECONDARY="#dfbdcc"
export MATUGEN_TERTIARY="#f3ba9b"
export MATUGEN_ERROR="#ffb4ab"
export MATUGEN_SURFACE="#181115"
export MATUGEN_ON_PRIMARY="#511d3d"
export MATUGEN_ON_SECONDARY="#402a35"
export MATUGEN_ON_SURFACE="#eddfe3"
export MATUGEN_OUTLINE="#9c8d93"
export MATUGEN_OUTLINE_VARIANT="#504349"

# Convert to 256 colors for p10k
export MATUGEN_PRIMARY_256=$(hex_to_256 "$MATUGEN_PRIMARY")
export MATUGEN_SECONDARY_256=$(hex_to_256 "$MATUGEN_SECONDARY")
export MATUGEN_TERTIARY_256=$(hex_to_256 "$MATUGEN_TERTIARY")
export MATUGEN_ERROR_256=$(hex_to_256 "$MATUGEN_ERROR")
export MATUGEN_ON_SURFACE_256=$(hex_to_256 "$MATUGEN_ON_SURFACE")

# Override Powerlevel10k colors
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=$MATUGEN_PRIMARY_256
typeset -g POWERLEVEL9K_DIR_BACKGROUND=$MATUGEN_SECONDARY_256
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=$MATUGEN_TERTIARY_256
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=$MATUGEN_SECONDARY_256
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=$MATUGEN_PRIMARY_256
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$MATUGEN_PRIMARY_256
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$MATUGEN_ERROR_256
