[config.wallpaper]
# Whether to set the wallpaper or not
set = false

# The base command to run for applying the wallpaper, shouldn't have spaces in it.
command = "swww"

# The arguments that will be provided to the command.
# Keywords like {{ mode }} or anything that works inside of hooks doesn't work here.
# The last argument will be the image path.
arguments = ["img", "--transition-type", "center"]

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = "hyprctl reload >/dev/null 2>&1"

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/current-theme.conf'
post_hook = 'kill -SIGUSR1 $(pgrep kitty)'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "~/.config/waybar/scripts/launch.sh"

[templates.p10k]
input_path = '~/.config/matugen/templates/p10k-colors.zsh'
output_path = '~/.config/zsh/matugen-p10k-colors.zsh'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync-style.css'
output_path = '~/.config/swaync/style.css'
post_hook = 'swaync-client -R'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux-colors.conf'
output_path = '~/.config/tmux/colors.conf'
post_hook = "tmux list-sessions -F '#S' 2>/dev/null | xargs -I {} tmux source-file -t {} ~/.config/tmux/colors.conf || true"
