id_ed25519.private.gpg=~/.ssh/id_ed25519
id_ed25519.pub.private.gpg=~/.ssh/id_ed25519.pub
id_ed25519.public.gpg=~/.ssh/id_ed25519
id_ed25519.pub.public.gpg=~/.ssh/id_ed25519.pub
credentials.gpg=~/.aws/credentials
