name: Test Scripts and Aliases

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install bats-core
      run: |
        sudo apt-get update
        sudo apt-get install -y bats

    - name: Run bats tests
      run: |
        bats ./workspace/tests

